### ISSUE TITLE
apiQuery() can fail under certain ingress scenarios

### ISSUE THREAD

**Issue by cohoe** [challfry/swiftarr#17]
Mostly using this issue as a point of documentation as it's definitely a low-priority thing.

### Summary

Swiftarr `apiQuery` calls may take unexpected paths under default configuration when fronted with a reverse proxy and/or ingress controller.

### Background

I deployed Swiftarr behind my local ingress controller (Traefik) which is configured with a self-signed wildcard TLS certificate. I have a public ingress controller (also Traefik) that automatically signs endpoints with the widely-trusted LetsEncrypt CA. I configured a reverse proxy to forward traffic hitting the public ingress controller to my private ingress controller. Flow is as follows:
```
{ Client Traffic } -> [ Public Ingress ] -> [ Reverse Proxy ] -> [ Private Ingress ] -> [ Swiftarr Pod ]
```

Client traffic in this situation would receive a 500 Internal Server Error stylized and returned from Swiftarr itself. My traffic was getting there OK but something caused Swiftarr to barf. Analyzing a packet capture taken within the pod revealed that calls from Swiftarr to itself (aka the `apiQuery()` method) were failing with an "Unknown CA" error. This led me to https://github.com/challfry/swiftarr/blob/ed13e188f2ff9c0a8ef9c16d44d41d7abe3c348b/Sources/App/Site/SiteController.swift#L430-L446

What was happening is that client traffic was arriving at the pod with an HTTP `Host` header set to the endpoint on my private ingress. Because `apiQuery` is essentially a call to itself Swiftarr was attempting to validate my self-signed CA within its runtime and failing. Clients are "unaffected" because their TLS connection terminates at the public ingress which is signed by a well-known CA. There is some processing by Swiftarr to auto-determine its "internal hostname" should a `Host` head be absent. By default within the Docker runtime config this would result in setting a `urlStr` of `"http://0.0.0.0:8081/api/v3/\(endpoint)"`. Fortunately this would be interpreted by the network stack to actually hit `127.0.0.1` which would work just fine. But the odds of not having a `Host` header are pretty slim since I'm pretty sure you have to do some voodoo to get there.

I was able to work around this issue by telling my private ingress to not forward the `Host` header from client requests. This yielded a result of requests arriving at Swiftarr with a `Host` header containing the internal Docker IP address of the pod, which works just fine for our purposes.

### Proposed Solutions

1. Since Swiftarr never really "cares" about the `Host` header, always default the internal API endpoint to the app configured hostname (`0.0.0.0` in the above example).
2. Add a configuration variable to the Private Swiftarr Config templates for `API_HOSTNAME` or `INTERNAL_HOSTNAME` or something like that and make that take priority over all of the other options, defaulting back to the `Host` header (and then the app configuration)

**Comment by cohoe** [comment]
Just hit a variant of this with a test install on the prod server. Service gave a 500 error after a long time. Curls from the container to the host:port would timeout. Container IP address was in a 172.9.0.0/16 net. Docker generally does some voodoo iptables chains to bypass certain firewall policies. This allowed access from the outside (ie, someones laptop on the same network possibly not beyond that) but not doing a hairpin from container to host [into container]. Opening the port to everywhere via `sudo ufw add 8081/tcp` made it work just fine.

**Comment by challfry** [comment]
I really wish Vapor had a way to perform internal HTTP calls that didn't go through the network loopback but did go through Vapor's tree router and trigger all the middleware.

The idea was that at some point in the future the front end could in theory be separated from the API and each part could be placed into its own Docker container or whatever. Even if that never happens, I'm a big believer in having a web front end that has to use the same API that native clients use. Just designing the front-end functions to call the API layer directly doesn't work because of all the work that the middleware does.

Adding a API_HOSTNAME configuration variable would probably help get us closer to being able to split the app into 2 parts.

**Comment by cohoe** [comment]
I definitely agree that the front end should use the same API as everyone else. While I haven't confirmed this in detail I don't believe much of the config `.env`'s actually apply to the front end (vs API service configuration, service deps, seeding, etc) other than the listening and endpoint. This could easily support being broken out into its own component taking a couple simple parameters of `API_HOSTNAME`, log level, and similar HTTP listening params. Might make maintaining a bit easier if contributors can narrow their focus to one component or the other without having to do a ton of reading to figure out what goes where.

**Comment by cohoe** [comment]
This prevented hitting twitarr.com:8081 from working because of weird DNS stuff on-boat (NAT).
