### ISSUE TITLE
Rework Barrels

### ISSUE THREAD

**Issue by challfry** [challfry/swiftarr#2]
Barrels are a way to store a list of UUIDs of database objects, or a list of strings, in the Postgres DB. Barrels are used both as a storage method for values wrapped in server APIs, and exposed directly in the API so clients can create barrels for client-specific purposes.

Barrels probably have value as a generic data store that client apps can use (although I think they could have *more* value as a shared store where multiple users share the same list). But, in all the cases where Barrels are the database storage method backing an API feature (blocks, mutes, mute words, alert words, bookmarks/favorites/tags) we'd be better served by storing the data in pivot tables (bookmarks, blocks and mutes), or in Redis as set-valued Redis keys (alert words, mute words). 

Redis sets can do everything Barrels can do but they're faster; Pivot tables have the advantage that we can load the linked objects in a single Fluent db call.

The good news with this change is that each BarrelType can be peeled off and reworked individually. Although, it might be possible to make a Bookmarkable protocol and conform Twarrts, Forums, ForumPosts, and Events to it.

**Comment by cohoe** [comment]
The entire concept of barrels was removed in https://github.com/challfry/swiftarr/commit/ed891389f873dc0ecc2d5bb40dbfd706b47f639e
